-- Conta do cliente (opcional): nome, celular, endereços salvos e acompanhamento dos pedidos
-- Rode no Supabase: Dashboard > SQL Editor > New query (depois do entrega-por-cep.sql).
-- Pode rodar mais de uma vez.
--
-- Segurança: cliente logado NÃO vira admin. O painel continua liberado só para quem
-- está na tabela admins (is_admin). Cada cliente só lê e altera os próprios dados.

-- =========================================================
-- 1. Dados do cliente (1 linha por conta do Supabase Auth)
-- =========================================================
create table if not exists public.clientes (
  id uuid primary key references auth.users (id) on delete cascade,
  nome text not null check (char_length(nome) between 1 and 120),
  -- DDD + número, só dígitos (ex.: 99981234567)
  telefone text not null unique check (telefone ~ '^\d{10,11}$'),
  criado_em timestamptz not null default now()
);

alter table public.clientes enable row level security;

drop policy if exists "Cliente le seus dados" on public.clientes;
create policy "Cliente le seus dados" on public.clientes
  for select to authenticated using (id = auth.uid() or public.is_admin());

drop policy if exists "Cliente cria seus dados" on public.clientes;
create policy "Cliente cria seus dados" on public.clientes
  for insert to authenticated with check (id = auth.uid());

drop policy if exists "Cliente edita seus dados" on public.clientes;
create policy "Cliente edita seus dados" on public.clientes
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

grant select, insert, update on public.clientes to authenticated;

-- =========================================================
-- 2. Endereços salvos ("Casa", "Trabalho"...)
-- =========================================================
create table if not exists public.enderecos (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null default auth.uid() references public.clientes (id) on delete cascade,
  apelido text not null default 'Casa' check (char_length(apelido) between 1 and 30),
  cep text check (char_length(cep) <= 9),
  bairro_id uuid references public.bairros (id) on delete set null, -- null: bairro fora da lista
  bairro text not null check (char_length(bairro) between 1 and 120),
  endereco text not null check (char_length(endereco) between 1 and 200), -- rua
  numero text not null check (char_length(numero) between 1 and 20),
  complemento text check (char_length(complemento) <= 120),
  cidade text check (char_length(cidade) <= 80),
  uf text check (char_length(uf) <= 2),
  localizacao text check (localizacao ~ '^-?\d{1,2}\.\d{1,8},-?\d{1,3}\.\d{1,8}$'),
  criado_em timestamptz not null default now()
);

create index if not exists enderecos_cliente_idx on public.enderecos (cliente_id);

alter table public.enderecos enable row level security;

drop policy if exists "Cliente gerencia seus enderecos" on public.enderecos;
create policy "Cliente gerencia seus enderecos" on public.enderecos
  for all to authenticated using (cliente_id = auth.uid()) with check (cliente_id = auth.uid());

grant select, insert, update, delete on public.enderecos to authenticated;

-- =========================================================
-- 3. Pedido ligado à conta: o cliente acompanha o status (novo, preparando, saiu...)
-- =========================================================
alter table public.pedidos add column if not exists cliente_id uuid references auth.users (id) on delete set null;
create index if not exists pedidos_cliente_idx on public.pedidos (cliente_id, criado_em desc);

-- O dono do pedido é sempre quem está logado (o navegador não escolhe; sem login fica null)
create or replace function public.pedido_do_cliente()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.cliente_id := auth.uid();
  return new;
end;
$$;

drop trigger if exists pedidos_cliente on public.pedidos;
create trigger pedidos_cliente
  before insert on public.pedidos
  for each row execute function public.pedido_do_cliente();

drop policy if exists "Cliente le seus pedidos" on public.pedidos;
create policy "Cliente le seus pedidos" on public.pedidos
  for select to authenticated using (cliente_id = auth.uid());

notify pgrst, 'reload schema';
