-- Rode este script no Supabase: Dashboard > SQL Editor > New query
-- Funciona tanto em banco novo quanto no banco que já tem categorias/produtos:
-- só cria o que falta, não apaga dados. Pode rodar mais de uma vez.

-- =========================================================
-- Tabelas (estrutura igual à já existente no projeto)
-- =========================================================

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text,
  icone text,
  ordem int not null default 0
);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  preco numeric(10,2) not null,
  imagem_url text,
  categoria_id bigint references public.categorias(id),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

-- Colunas usadas pelo painel que ainda não existiam
alter table public.categorias add column if not exists ativo boolean not null default true;
alter table public.produtos add column if not exists ordem int not null default 0;

-- Usuários que podem acessar o painel de administração
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

-- =========================================================
-- Função auxiliar: o usuário logado é admin?
-- =========================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

-- =========================================================
-- RLS (segurança por linha)
-- Remove as políticas antigas de categorias/produtos (criadas por fora)
-- para que só o admin consiga alterar dados.
-- =========================================================

do $$
declare p record;
begin
  for p in
    select policyname, tablename from pg_policies
    where schemaname = 'public' and tablename in ('categorias', 'produtos')
  loop
    execute format('drop policy %I on public.%I', p.policyname, p.tablename);
  end loop;
end $$;

alter table public.categorias enable row level security;
alter table public.produtos enable row level security;
alter table public.admins enable row level security;

-- Loja: qualquer visitante lê o que estiver ativo
create policy "Publico le categorias ativas" on public.categorias
  for select to anon, authenticated using (ativo = true);

create policy "Publico le produtos ativos" on public.produtos
  for select to anon, authenticated using (ativo = true);

-- Painel: admin lê e altera tudo
create policy "Admin gerencia categorias" on public.categorias
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admin gerencia produtos" on public.produtos
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- =========================================================
-- Storage: imagens dos produtos (bucket público)
-- =========================================================

insert into storage.buckets (id, name, public)
values ('produtos', 'produtos', true)
on conflict (id) do update set public = true;

drop policy if exists "Admin envia imagens" on storage.objects;
create policy "Admin envia imagens" on storage.objects
  for insert to authenticated with check (bucket_id = 'produtos' and public.is_admin());

drop policy if exists "Admin atualiza imagens" on storage.objects;
create policy "Admin atualiza imagens" on storage.objects
  for update to authenticated using (bucket_id = 'produtos' and public.is_admin());

drop policy if exists "Admin remove imagens" on storage.objects;
create policy "Admin remove imagens" on storage.objects
  for delete to authenticated using (bucket_id = 'produtos' and public.is_admin());

-- =========================================================
-- Depois de criar seu usuário em Authentication > Users,
-- torne-o admin (troque o e-mail):
--
-- insert into public.admins (user_id)
-- select id from auth.users where email = 'seu@email.com';
-- =========================================================
